### ISSUE TITLE
1º Logica basica

### ISSUE THREAD

**Issue by Clovisindo** [Clovisindo/Balatro-like#2]
## Motivación
1º crear una carta que registre eventos de  clicable
- [x] Hacer que se pueda clicar y te siga de mientras y cambie de color en el proceso

2º crear un hueco de interfaz donde se guardan las cartas de la mano
- [x] Si las arrastras fuera y sueltas, vuelven a la posicion inicial ( primero con una sola carta y llendo al (0,0) sin montar logica ninguna

3º crear un panel de ordenar, que contenga todas las cartas hijas dentro y se adecue en forma y tamaño
- [x] Como se van a comunicar? por signals de cada carta?

    
4º Card swap behaviour
- [x]    El panel contenedor tendrá un script que guardará la carta actual que está hovered, recuerda que solo habra una en cada estado asi que solo guardas una., las selected se guardan cada una en su carta
- [x]     Metodo que va comprobando la carta mayor y la mejor, y luego actualiza la que está drageada

5º Final si hay una carta selecionada, la mueves un poco hacia arriba y cambiars color

## Criterios
Cada elemento carta tenga las funciones y efectos para : 
Drag: clicar en ella y poder moverla siguiendo el raton.
Hovered: que al clicar encima haga efecto.
Selected: que haga efecto de moverse para ver que esta selecionada.
Crear gestor de cartas en mano y que vuelvan ahi cuando las muevas.
Añadir al gesto que ordene las cartas si las cambias de posiciones, se adapte en tamaño y demás.
Al gestor de cartas añadir una funcion de reordenar las cartas.
Modo selected a las cartas.
