### ISSUE TITLE
2º diseño visual y lerp animaciones

### ISSUE THREAD

**Issue by Clovisindo** [Clovisindo/Balatro-like#9]
## Motivación
Como las animaciones asi son muy estaticas, creamos un prefab de visual, que va a seguir al objeto que tiene la logica, con un lerp, y asi tener un movimiento mas suave al arrastrar y todas las demas modificaciones que hagamos

- [x] Añadir que la parte visual escuche a tods los eventos que cambian la logica de la carta, para tener implementado aparte el cambio visual.
- [x] Cuando se coge una carta se sube su posicion haciendola aparecer a mas altura que el resto de la mano.
- [x] el movimiento siguiendo con lerp a una parte visual separada para simular retraso
- [x] Añadir que cuando esta en hovered, la carta se incline al moverse.
- [x] Shake cuando pasas el raton por encima ( en estado idle)
- [x] Animacion de "position punch" que sube, pero haga un rebote simulando un choque final.
- [x] Hacer que la carta se dibuje por encima de las demas cartas cuando está hovered.
- [x] Se añade sombra para añadir profundidad, solo cuando está en estado hovered.

    

## Criterios

- [x] Cumplir con las animaciones definidas:
- [x] Retraso de seguimiento en hovered.
- [x] Rotacion en el seguimiento en hovered.
- [ ] Shake al pasar el raton por encima en idle.
- [x] Position punch al cambiar a selected.
- [x] Hacer que la carta se dibuje por encima en hovered.
- [x] Sombra en hovered.

**Comment by Clovisindo** [comment]
EN principio dejamos la animacion de cambio de estado a selected como está , funciona bien en lugar del efecto "push up" que hace con DoTween
